sudo: required
language: java
jdk: openjdk11

# NOTE(Jovan): Disable email spamming
notifications:
  email: false

services:
  - postgresql

before_install:
  - chmod +x mvnw

before_script:
  - psql -c "CREATE DATABASE isadb;" -U postgres
  - psql -c "CREATE USER isa WITH PASSWORD 'isa';" -U postgres

addons:
  sonarcloud:
    organization: "schnabelorg"
    token: $SONAR_TOKEN


script:
  - ./mvnw clean install -DskipTests=false -B
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ./mvnw sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=schnabelorg -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

    
# NOTE(Jovan): Send success/failure messages to Discord server
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: schnabel
