# Spring Boot configuration
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL} #jdbc:postgresql://localhost:5432/isadb
    username: ${JDBC_DATABASE_USERNAME} #isa 
    password: ${JDBC_DATABASE_PASSWORD} #isa 
    initialization-mode: always
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop #create-drop # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  # RabbitMQ ONLY WHEN USING ON LOCAL MACHINE
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: vmaqngrm
#    password: BHAFy2pYqDLrQxDduUD-03HH-N0ACEVW
custom:
  port: ${SCHNABEL_PORT}
